ignore:
    - "alphatwirl/_version.py"
    - "alphatwirl/heppyresult/*"
    - "alphatwirl/delphes/*"
    - "alphatwirl/cmsedm/*"
    - "tests/unit/heppyresult/*"
    - "tests/unit/delphes/*"
    - "tests/ROOT/*"
    - "tests/dataframe/*"
    - "tests/misc/*"
